%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.2

-ifndef(goblet_pb).
-define(goblet_pb, true).

-define(goblet_pb_gpb_version, "4.11.2").

-ifndef('GENRESPONSE_PB_H').
-define('GENRESPONSE_PB_H', true).
-record('GenResponse',
        {status                 :: 'OK' | 'ERROR' | integer(), % = 1, enum GenResponse.Status
         msg                    :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ACCOUNTNEWREQ_PB_H').
-define('ACCOUNTNEWREQ_PB_H', true).
-record('AccountNewReq',
        {email                  :: iodata(),        % = 1
         password               :: iodata()         % = 2
        }).
-endif.

-ifndef('ACCOUNTLOGINREQ_PB_H').
-define('ACCOUNTLOGINREQ_PB_H', true).
-record('AccountLoginReq',
        {email                  :: iodata(),        % = 1
         password               :: iodata()         % = 2
        }).
-endif.

-ifndef('CLIENTLOG_PB_H').
-define('CLIENTLOG_PB_H', true).
-record('ClientLog',
        {msg                    :: iodata()         % = 2
        }).
-endif.

-endif.
