%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.2

-ifndef(goblet_pb).
-define(goblet_pb, true).

-define(goblet_pb_gpb_version, "4.11.2").

-ifndef('ACCOUNTNEWREQ_PB_H').
-define('ACCOUNTNEWREQ_PB_H', true).
-record('AccountNewReq',
        {email                  :: iodata(),        % = 1
         password               :: iodata()         % = 2
        }).
-endif.

-ifndef('ACCOUNTNEWRESP_PB_H').
-define('ACCOUNTNEWRESP_PB_H', true).
-record('AccountNewResp',
        {status                 :: 'OK' | 'ERROR' | integer(), % = 1, enum AccountNewResp.Status
         error                  :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('ACCOUNTLOGINREQ_PB_H').
-define('ACCOUNTLOGINREQ_PB_H', true).
-record('AccountLoginReq',
        {email                  :: iodata(),        % = 1
         password               :: iodata()         % = 2
        }).
-endif.

-ifndef('ACCOUNTLOGINRESP.PLAYER_PB_H').
-define('ACCOUNTLOGINRESP.PLAYER_PB_H', true).
-record('AccountLoginResp.Player',
        {name                   :: iodata()         % = 1
        }).
-endif.

-ifndef('ACCOUNTLOGINRESP_PB_H').
-define('ACCOUNTLOGINRESP_PB_H', true).
-record('AccountLoginResp',
        {status                 :: 'OK' | 'ERROR' | integer(), % = 1, enum AccountLoginResp.Status
         players = []           :: [goblet_pb:'AccountLoginResp.Player'()] | undefined, % = 2
         error                  :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('PLAYERNEWREQ_PB_H').
-define('PLAYERNEWREQ_PB_H', true).
-record('PlayerNewReq',
        {name                   :: iodata(),        % = 1
         title                  :: iodata(),        % = 2
         appearance             :: non_neg_integer(), % = 3, 32 bits
         role                   :: iodata()         % = 4
        }).
-endif.

-ifndef('PLAYERNEWRESP_PB_H').
-define('PLAYERNEWRESP_PB_H', true).
-record('PlayerNewResp',
        {status                 :: 'OK' | 'ERROR' | integer(), % = 1, enum PlayerNewResp.Status
         error                  :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('PLAYERAUTHENTICATE_PB_H').
-define('PLAYERAUTHENTICATE_PB_H', true).
-record('PlayerAuthenticate',
        {id                     :: iodata()         % = 1
        }).
-endif.

-ifndef('PLAYERLOG_PB_H').
-define('PLAYERLOG_PB_H', true).
-record('PlayerLog',
        {msg                    :: iodata()         % = 2
        }).
-endif.

-ifndef('OBJECTGET_PB_H').
-define('OBJECTGET_PB_H', true).
-record('ObjectGet',
        {id                     :: iodata(),        % = 1
         object                 :: 'ROOM' | 'ENTITY' | 'SCRIPT' | integer(), % = 2, enum ObjectGet.GameObject
         oid                    :: iodata() | undefined, % = 3
         name                   :: iodata() | undefined % = 4
        }).
-endif.

-ifndef('SHELLCOMMAND_PB_H').
-define('SHELLCOMMAND_PB_H', true).
-record('ShellCommand',
        {id                     :: iodata(),        % = 1
         command                :: iodata()         % = 2
        }).
-endif.

-ifndef('ROOM_PB_H').
-define('ROOM_PB_H', true).
-record('Room',
        {name                   :: iodata(),        % = 1
         ownerid                :: iodata(),        % = 2
         description            :: iodata(),        % = 3
         backlink               :: boolean() | 0 | 1, % = 4
         link = []              :: [iodata()] | undefined, % = 5
         entity = []            :: [goblet_pb:'Entity'()] | undefined, % = 6
         script = []            :: [goblet_pb:'LuaScript'()] | undefined % = 7
        }).
-endif.

-ifndef('ENTITY_PB_H').
-define('ENTITY_PB_H', true).
-record('Entity',
        {id                     :: iodata(),        % = 1
         name                   :: iodata(),        % = 2
         room                   :: iodata()         % = 3
        }).
-endif.

-ifndef('LUASCRIPT_PB_H').
-define('LUASCRIPT_PB_H', true).
-record('LuaScript',
        {id                     :: iodata(),        % = 1
         name                   :: iodata() | undefined, % = 2
         content                :: iodata()         % = 3
        }).
-endif.

-endif.
