-define(PROTOCOLVERSION, 1).

% First two bytes of a message are its opcode which maps onto RPCs supported by and informational messages generated by the server

% General commands
-define(VERSION, 16#1000).
-define(HEARTBEAT, 16#1010).
-define(ACCOUNT_NEW, 16#1040).
-define(ACCOUNT_LOGIN, 16#1045).
-define(PLAYER_NEW, 16#1050).
-define(PLAYER_LOGIN, 16#1055).
-define(PLAYER_LOG, 16#1060).

% Lobby and match creation commands
-define(LOBBY_INFO, 16#2010).
-define(MATCH_CREATE, 16#2020).
-define(MATCH_JOIN, 16#2030).
-define(MATCH_LEAVE, 16#2040).

%%%% Deprecated

% Room-specific commands
-define(ROOM_STATE, 16#1100).
%-define(PLAYER_MOVE, 16#1230).

% Entity-specific commands
-define(ENTITY_STATE, 16#1300).
-define(ENTITY_VALIDATE, 16#1310).
-define(ENTITY_COMMIT, 16#1320).
-define(ENTITY_DELETE, 16#1330).
-define(ENTITY_RANDNAME, 16#1340).

% Script-specific commands
-define(SCRIPT_STATE, 16#1500).
-define(SCRIPT_VALIDATE, 16#1510).
-define(SCRIPT_COMMIT, 16#1520).
-define(SCRIPT_DELETE, 16#1530).
